logging:
  level: info

storage:
  options_data:
    provider: postgres
    host: localhost
    port: 5432
    user_name: optimal_user
    schema_name: options_data

credentials:
  provider: cred-file